apiVersion: v1
kind: Service
metadata:
  name: adoptmeservice
spec:
  selector:
    app: adoptmepod
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30008
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: adoptmedeployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: adoptmepod
  template:
    metadata:
      labels:
        app: adoptmepod
    spec:
      containers:
      - name: adoptmecontainer
        image: mauroluque1/addoptme:1.0.0
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_URI
          value: "mongodb+srv://mauroluque72:Fg6NAmMPPoBhSuFJ@addoptme.fvwg9im.mongodb.net/backendsabados?retryWrites=true&w=majority&appName=Addoptme"
        - name: MODE
          value: "prod"
        imagePullPolicy: Always